### ISSUE TITLE
emetabolomics offline, errors not handled properly

### ISSUE THREAD

**Issue by jspaaks** [NLeSC/collab-demos#101]
```bash 
$ python3 src/makereadme.py
checking "http://ahn2.pointclouds.nl/"...
checking "https://github.com/NLeSC/collab-demos/blob/master/demos/ahn2/README.md"...
checking "https://vimeo.com/154200270"...
checking "https://github.com/NLeSC/ahn-pointcloud-viewer"...
checking "https://nlesc.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FShared%20Documents%2FNLeSC%20Project%20Presentations%2FClosed%2FMassive%20point%20cloud%20for%20eSciences&FolderCTID=0x0120004EB0DBA245A10041AA401E78745EB1B1&View={2CC9F224-02CB-49B5-9DBB-C97AE29C8572}"...
checking "http://nlesc.github.io/eEcology-Annotation-UI/demo/demo.html"...
checking "https://github.com/NLeSC/collab-demos/blob/master/demos/eecology-annotation-ui/README.md"...
checking "https://vimeo.com/158029473"...
checking "https://github.com/NLeSC/eEcology-Annotation-UI"...
checking "https://nlesc.sharepoint.com/Shared%20Documents/Forms/AllItems.aspx?RootFolder=%2FShared%20Documents%2FNLeSC%20Project%20Presentations%2FCurrent%2FeEcology&FolderCTID=0x0120004EB0DBA245A10041AA401E78745EB1B1&View={2CC9F224-02CB-49B5-9DBB-C97AE29C8572}"...
checking "http://www.emetabolomics.org/green_tea_hmdb.html"...
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 137, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 91, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 81, in create_connection
    sock.connect(sa)
OSError: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 560, in urlopen
    body=body, headers=headers)
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 162, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 146, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
requests.packages.urllib3.exceptions.NewConnectionError: <requests.packages.urllib3.connection.HTTPConnection object at 0x7fd332f1fe48>: Failed to establish a new connection: [Errno 113] No route to host

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 376, in send
    timeout=timeout
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 610, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 273, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
requests.packages.urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='www.emetabolomics.org', port=80): Max retries exceeded with url: /green_tea_hmdb.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd332f1fe48>: Failed to establish a new connection: [Errno 113] No route to host',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src/makereadme.py", line 97, in <module>
    readmeMaker.writemarkdown()
  File "src/makereadme.py", line 83, in writemarkdown
    linkify(entry['urls']['demo']),
  File "src/makereadme.py", line 44, in linkify
    request = requests.get(url, timeout=30.0)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 67, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/api.py", line 53, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 468, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 576, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 437, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='www.emetabolomics.org', port=80): Max retries exceeded with url: /green_tea_hmdb.html (Caused by NewConnectionError('<requests.packages.urllib3.connection.HTTPConnection object at 0x7fd332f1fe48>: Failed to establish a new connection: [Errno 113] No route to host',))

```

**Comment by jspaaks** [comment]
[this](https://github.com/NLeSC/collab-demos/blob/cfd62946676eb633068bb084ce1d0e1ee132eca3/src/makereadme.py#L44) is the line that results in an error (with ``url`` = ``'http://www.emetabolomics.org/green_tea_hmdb.html'``)
